global:
  smscSim:
    clusterIP: "10.100.176.220"

image_shas:
  my_sample_application: abcdefgh
  another_repo: abcdef

dish-smsf-svc:
  service:
    ports:
      httpNFServer:
        nodePort: 32081
      httpsNFServer: 
        nodePort: 32082

dish-smsf-emagt:
  service:
    emagtWs:
      ports:
        ws:
          nodePort: 32401
        stat:
          nodePort: 32402
          targetPort: 32402

dish-smsf-emgui:
  service:
    ports:
      nginx:
        nodePort: 32336
